# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 07ea92a4a01ae9c9bd3b663bb3644adeb8f65231a9a02eb7c43649b90c36f1f0f3d7119cc6446e29592a57d85c125f79887258fe21b4a5347ed029959f3a509a

test:
  secret_key_base: 121321c1d99f743fd167f501c88183145b942ce236cedf28f8d1a3f6419e169de7d3b9066487ecb99fe410ecb49cb79d28b013a03e00549d0442fe7ba7a83278

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
